### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by pbrisbin** [freckle/faktory_worker_haskell#40]
v1.0.0.0 is latest on Hackage and is missing 20f58a70d31b1dd1296a98c4d835bd4175a26028, that means it can't be used in the latest LTS. We should release a new version with this fix.

**Comment by eborden** [comment]
Gonna have to fiddle with cabal bounds before going to hackage, since the only real problem is the mega-parsec bump.

**Comment by pbrisbin** [comment]
Yeah, I think were probably supposed to move the lower bound on that dep when we introduced that commit that relied on the new thing (assuming there was no backwards-compatible way we wanted to do it).

**Comment by pbrisbin** [comment]
> Yeah, I think were probably supposed to move the lower bound 

Oh sorry, I just checked the commit and you already did that.

> Gonna have to fiddle with cabal bounds

So, can you be more specific then? It seems fine to me as is.

**Comment by eborden** [comment]
Woops, yeah looks like I did already do that. As for the version number the PVP says this:

> Note that modifying imports or depending on a newer version of another package may cause extra orphan instances to be exported and thus force a major version change.

**Comment by pbrisbin** [comment]
Got it. I personally tend to take a best-effort approach to that particular rule. Like, I think it's unlikely updating megaparsec brought in new orphan instances. So, without actually digging around a real diff, I'd probably bump my own version under the assumption it didn't. WDYT? Would you ranter take on the extra due-diligence there?

**Comment by eborden** [comment]
I'm okay with that. Personally bumping for orphans is a bit too aggressive for me.

**Comment by pbrisbin** [comment]
http://hackage.haskell.org/package/faktory-1.0.1.0
