### ISSUE TITLE
Suggestion: runWorkerHandle

### ISSUE THREAD

**Issue by pbrisbin** [freckle/faktory_worker_haskell#42]
## Motivation

In the README, we have:

```hs
workerMain = do
  settings <- envSettings

  runWorker settings $ \job ->
    -- Process your Job here
    putStrLn $ myJobMessage job

    -- If any exception is thrown, the job will be marked as Failed in Faktory
    -- and retried. Note: you will not otherwise hear about any such exceptions,
    -- unless you catch-and-rethrow them yourself.
```

That comment had me thinking:

```hs
workerMain = do
  settings <- envSettings

  runWorkerHandle settings
    (\ex ->
      -- Do something with any processing exceptions
      hPutStrLn stderr $ show ex
    )
    (\job ->
      -- Process your Job here
      putStrLn $ myJobMessage job
    )
```

would be a nice way to allow users to observe exceptions but avoid them forgetting to re-throw and ensure the Job gets marked Failed in Faktory.

Currently, this is accomplished with (e.g.):

```hs
workerMain = do
  settings <- envSettings

  runWorker settings $ \job -> handleAny f $ do
    -- Process your Job here
    putStrLn $ myJobMessage job

f ex = do
  hPutStrLn stderr $ show ex
  throwIO ex -- <-- important to remember!
```

## Naming Alternatives

The naming is TBD, but I took it from the idea that `handle` takes the exception handler first, which I like here because:

```hs
runWorker settings = runWorkerHandle settings $ const $ pure ()
```

`runWorkerCatch` is another obvious name, but that would imply (IMO) that the exception handler is taken second, which doesn't compose as nicely to `runWorker`. We could easily provide both.

`runWorkerHandling` and/or `runWorkerCatching` are other decent name choices, IMO.

**Comment by ZzAntares** [comment]
About the `runWorkerHandle` it seems more natural to get the result wrapped in an `Either` instead of two callback functions, i. e:

```hs
  runWorkerHandle settings $ \case
    Left ex ->
      -- Do something with any processing exceptions
      hPutStrLn stderr $ show ex

    Right job ->
      -- Process your Job here
      putStrLn $ myJobMessage job
```

Just thinking out loud 😄

**Comment by pbrisbin** [comment]
That's a good idea, I like that a lot. I would probably want to brainstorm some other names, since the inspiration for "handle" was the real `handle` function. Maybe we use "try" somehow, since that's sort of the same in that it takes exception-handling and makes it `Either`? So `runWorkerTry`?

**Comment by pbrisbin** [comment]
Closing as stale. If anyone wants to re-open and work on something in this direction, feel free!
