### ISSUE TITLE
Allow workers to specify a name

### ISSUE THREAD

**Issue by liftM** [freckle/faktory_worker_haskell#48]
Right now, it looks like the worker name (as viewed in the busy dashboard in the Faktory UI) is set automatically by combining the Faktory server hostname and the worker's process ID. Since my workers all connect to the same Faktory server and they are all forks running in the same process, all of my workers appear to have the same name in the Faktory UI. This, combined with #47, makes it very difficult to tell what Faktory believes what any particular worker's job is.

I would like to be able to specify the worker's name as a setting.

**Comment by pbrisbin** [comment]
Do you know where in the Faktory API you can tell it the Worker's name? I can't find anything in this [wiki](https://github.com/contribsys/faktory/wiki). I was guessing it was something to send in the Hello payload, along with Worker Id, but it's not.

```
HELLO {
 "hostname":"MikeBookPro.local",
 "wid":"4qpc2443vpvai",
 "pid":2676,
 "labels":["golang"],
 "pwdhash":"1e440e3f3d2db545e9129bb4b63121b6b09d594dae4344d1d2a309af0e2acac1",
 "v":2
}
> OK
```

**Comment by pbrisbin** [comment]
Closing as Stale. Please re-open if you're able to provide more details about how to do this.
