### ISSUE TITLE
Faktory timeout is not handled

### ISSUE THREAD

**Issue by eborden** [freckle/faktory_worker_haskell#71]
Faktory utilizes a timeout for all jobs. A job must `Ack` within a given period or Faktory will assume it has died and retry (or let die) the respective job. This property can be set with `reserve_for` and is described in the [worker lifecycle](https://github.com/contribsys/faktory/wiki/Worker-Lifecycle#executing-jobs) wiki entry.

`faktory_worker_haskell` does not utilize this timeout. This can result in _zombie_ jobs. A worker that exceeds the `reserve_for` will continue functioning while Faktory may have passed the job to another worker. This can cause duplicate effort, performance issues, and logical bugs.

Faktory worker should utilize the `reserve_for` to set an internal timeout. This timeout can `throwTo` the appropriate thread, ensuring operational consistency with Faktory and avoiding duplicate work issues.

**Comment by pbrisbin** [comment]
:+1:

I think we will need to hard-code the knowledge of Faktory's default behavior somewhere. We can either:

- Update the library's enqueue to add a `reserve_for: 1800` (hard-coded here) if the user did not specify, and
- Always expected a `reserve_for` on consume, to use as our `timeout`

Or

- Do not update the enqueue behavior at all
- Look for `reserve_for` on consume, and default to 1800 _then_

Are there any trade-offs between these two? I think the latter may be simpler, but I'm not sure.

**Comment by pbrisbin** [comment]
I'm also curious why the `throwTo` is being prescribed. I imagine this would look something like:

```diff
-processorLoop client settings workerSettings f = do
+processorLoop client settings workerSettings f = do
+  mVal <- timeout x $ do
+  maybe (throwIO JobExpired) pure $ mVal
```

**Comment by eborden** [comment]
This has been merged into main, but is unreleased.

**Comment by pbrisbin** [comment]
Thank you for tackling this! Awesome that it can be fully library-handled.
